/**
 * Nationalities offered in the signup form's searchable dropdown.
 *
 * The value stored on the child row is the English label, so existing records
 * (which were free text, mostly "Egyptian") keep rendering unchanged.
 */
export type Nationality = { en: string; ar: string };

export const NATIONALITIES: Nationality[] = [
  { en: 'Egyptian', ar: 'مصري' },
  { en: 'Saudi', ar: 'سعودي' },
  { en: 'Emirati', ar: 'إماراتي' },
  { en: 'Kuwaiti', ar: 'كويتي' },
  { en: 'Qatari', ar: 'قطري' },
  { en: 'Bahraini', ar: 'بحريني' },
  { en: 'Omani', ar: 'عماني' },
  { en: 'Yemeni', ar: 'يمني' },
  { en: 'Jordanian', ar: 'أردني' },
  { en: 'Palestinian', ar: 'فلسطيني' },
  { en: 'Lebanese', ar: 'لبناني' },
  { en: 'Syrian', ar: 'سوري' },
  { en: 'Iraqi', ar: 'عراقي' },
  { en: 'Sudanese', ar: 'سوداني' },
  { en: 'Libyan', ar: 'ليبي' },
  { en: 'Tunisian', ar: 'تونسي' },
  { en: 'Algerian', ar: 'جزائري' },
  { en: 'Moroccan', ar: 'مغربي' },
  { en: 'Mauritanian', ar: 'موريتاني' },
  { en: 'Somali', ar: 'صومالي' },
  { en: 'Djiboutian', ar: 'جيبوتي' },
  { en: 'Comorian', ar: 'قمري' },
  { en: 'Turkish', ar: 'تركي' },
  { en: 'Iranian', ar: 'إيراني' },
  { en: 'Pakistani', ar: 'باكستاني' },
  { en: 'Indian', ar: 'هندي' },
  { en: 'Bangladeshi', ar: 'بنغلاديشي' },
  { en: 'Sri Lankan', ar: 'سريلانكي' },
  { en: 'Nepalese', ar: 'نيبالي' },
  { en: 'Afghan', ar: 'أفغاني' },
  { en: 'Indonesian', ar: 'إندونيسي' },
  { en: 'Malaysian', ar: 'ماليزي' },
  { en: 'Filipino', ar: 'فلبيني' },
  { en: 'Chinese', ar: 'صيني' },
  { en: 'Japanese', ar: 'ياباني' },
  { en: 'Korean', ar: 'كوري' },
  { en: 'Nigerian', ar: 'نيجيري' },
  { en: 'Ghanaian', ar: 'غاني' },
  { en: 'Kenyan', ar: 'كيني' },
  { en: 'Ethiopian', ar: 'إثيوبي' },
  { en: 'Eritrean', ar: 'إريتري' },
  { en: 'South African', ar: 'جنوب أفريقي' },
  { en: 'Tanzanian', ar: 'تنزاني' },
  { en: 'Ugandan', ar: 'أوغندي' },
  { en: 'Senegalese', ar: 'سنغالي' },
  { en: 'Ivorian', ar: 'إيفواري' },
  { en: 'Cameroonian', ar: 'كاميروني' },
  { en: 'British', ar: 'بريطاني' },
  { en: 'Irish', ar: 'إيرلندي' },
  { en: 'French', ar: 'فرنسي' },
  { en: 'German', ar: 'ألماني' },
  { en: 'Italian', ar: 'إيطالي' },
  { en: 'Spanish', ar: 'إسباني' },
  { en: 'Portuguese', ar: 'برتغالي' },
  { en: 'Dutch', ar: 'هولندي' },
  { en: 'Belgian', ar: 'بلجيكي' },
  { en: 'Swiss', ar: 'سويسري' },
  { en: 'Austrian', ar: 'نمساوي' },
  { en: 'Swedish', ar: 'سويدي' },
  { en: 'Norwegian', ar: 'نرويجي' },
  { en: 'Danish', ar: 'دنماركي' },
  { en: 'Finnish', ar: 'فنلندي' },
  { en: 'Polish', ar: 'بولندي' },
  { en: 'Czech', ar: 'تشيكي' },
  { en: 'Hungarian', ar: 'مجري' },
  { en: 'Romanian', ar: 'روماني' },
  { en: 'Bulgarian', ar: 'بلغاري' },
  { en: 'Greek', ar: 'يوناني' },
  { en: 'Russian', ar: 'روسي' },
  { en: 'Ukrainian', ar: 'أوكراني' },
  { en: 'Kazakh', ar: 'كازاخي' },
  { en: 'Azerbaijani', ar: 'أذربيجاني' },
  { en: 'American', ar: 'أمريكي' },
  { en: 'Canadian', ar: 'كندي' },
  { en: 'Mexican', ar: 'مكسيكي' },
  { en: 'Brazilian', ar: 'برازيلي' },
  { en: 'Argentine', ar: 'أرجنتيني' },
  { en: 'Colombian', ar: 'كولومبي' },
  { en: 'Chilean', ar: 'تشيلي' },
  { en: 'Australian', ar: 'أسترالي' },
  { en: 'New Zealander', ar: 'نيوزيلندي' },
  { en: 'Other', ar: 'أخرى' },
];

export function nationalityOptions(preferArabic: boolean) {
  return NATIONALITIES.map((nationality) => ({
    value: nationality.en,
    label: preferArabic ? nationality.ar : nationality.en,
  }));
}
