export interface NurserySettingsRow {
  id: string;
  nursery_id: string;
  standard_start_time: string | null;
  standard_end_time: string | null;
  late_pickup_grace_minutes: number | null;
  late_pickup_fee_per_hour: string | null;
  auto_late_pickup_billing_enabled: boolean | null;
  require_qr_for_attendance: boolean | null;
  late_billing_unit_minutes: 15 | 30 | 60 | null;
  late_billing_from: 'end_time' | 'grace_end' | null;
  /** closing_time: extra hours start at closing; stay_duration: after the package's daily hours from check-in. */
  late_billing_base: 'closing_time' | 'stay_duration' | null;
  late_sweep_cap_hours: number | null;
  early_arrival_billing_enabled: boolean | null;
  late_invoice_mode: 'daily' | 'monthly' | null;
  pickup_reminder_minutes_before: number | null;
  min_minutes_between_scans: number | null;
  absence_alert_time: string | null;
  end_of_day_checklist_time: string | null;
  permission_deadline_default_hours: number | null;
  event_cancellation_window_hours: number | null;
  paid_event_refund_policy: 'full' | 'partial' | 'none' | null;
  quiet_hours_start: string | null;
  quiet_hours_end: string | null;
  max_whatsapp_per_parent_per_day: number | null;
  allow_parent_quiet_hours_override: boolean | null;
  auto_payment_reminders_enabled: boolean | null;
  auto_permission_reminders_enabled: boolean | null;
  auto_monthly_teacher_reminders_enabled: boolean | null;
  parent_registration_enabled: boolean | null;
  show_event_attendee_list: boolean | null;
  pricing_model: 'fixed' | 'per_child' | 'hourly' | 'hybrid' | null;
  monthly_rate: string | null;
  per_child_rate: string | null;
  hourly_rate: string | null;
  invoice_due_days: number | null;
  late_payment_fee_percentage: string | null;
  sibling_discount_2nd_child_percentage: string | null;
  sibling_discount_3rd_child_percentage: string | null;
  payment_methods_enabled: string[] | null;
  /** Where parents send transfers (InstaPay address, wallet number, bank account), shown on the pay page. */
  payment_instructions: string | null;
  summer_pause_enabled: boolean | null;
  summer_pause_min_weeks: number | null;
  summer_pause_max_weeks: number | null;
  summer_pause_auto_start_date: string | null;
  summer_pause_auto_end_date: string | null;
  summer_pause_charges_percentage: string | null;
  photo_approval_required: boolean | null;
  photo_auto_approve_after_hours: number | null;
  video_enabled: boolean | null;
  max_photo_per_child_per_day: number | null;
  cctv_enabled: boolean | null;
  cctv_stream_token_duration_minutes: number | null;
  cctv_max_concurrent_viewers_per_camera: number | null;
  cctv_recording_retention_days: number | null;
  loyalty_enabled: boolean | null;
  points_per_egp: string | null;
  points_redemption_rate: string | null;
  loyalty_tier_thresholds: { silver?: number; gold?: number; platinum?: number } | null;
  default_language: 'ar' | 'en' | null;
  timezone: string | null;
  currency: string | null;
  date_format: string | null;
  primary_color: string | null;
  secondary_color: string | null;
  accent_color: string | null;
  created_at: string;
  updated_at: string;
}
