import type { StaffOnboardingFormValues } from './staffOnboardingTypes';

export const STAFF_ONBOARDING_STORAGE_KEY = 'xo-staff-onboarding-draft-v1';

export function getDefaultStaffOnboardingValues(): StaffOnboardingFormValues {
  return {
    nurseryLanguagePref: 'both',
    userMode: 'new',
    newNameAr: '',
    newNameEn: '',
    newMobile: '',
    newEmail: '',
    existingUserId: '',
    employeeId: '',
    position: 'teacher',
    department: 'teaching',
    employmentType: 'full_time',
    startDate: new Date().toISOString().slice(0, 10),
    contractEndDate: '',
    contractAutoRenewal: false,
    probationEndDate: '',
    baseSalary: '',
    allowanceTransport: '',
    allowanceHousing: '',
    allowanceMeal: '',
    allowancePhone: '',
    paymentMethod: 'bank_transfer',
    bankName: '',
    bankAccountNumber: '',
    bankIban: '',
    workingDays: [0, 1, 2, 3, 4],
    workStartTime: '08:00',
    workEndTime: '16:00',
    nationalId: '',
    socialInsuranceNumber: '',
    taxId: '',
    dateOfBirth: '',
    gender: '' as const,
    maritalStatus: '',
    dependents: '0',
    criminalCheckDate: '',
    criminalStatus: '',
    ref1Name: '',
    ref1Phone: '',
    ref1Verified: '',
    ref2Name: '',
    ref2Phone: '',
    ref2Verified: '',
    childProtectionTrainingDate: '',
    educationDegree: '',
    teachingCertificate: '',
    yearsExperience: '',
    emergencyName: '',
    emergencyRelationship: '',
    emergencyPhone: '',
    termsAccepted: false,
  };
}
