import type { AllergyRow, ChildEnrollmentFormValues } from './childEnrollmentTypes';

export const DEFAULT_ALLERGY_PROTOCOL_EN = 'Call parent immediately';

export function defaultAllergyRow(): AllergyRow {
  return {
    allergenKey: 'peanuts',
    allergenOther: '',
    severity: 'mild',
    notes: '',
    protocol: DEFAULT_ALLERGY_PROTOCOL_EN,
  };
}

export const CHILD_ENROLLMENT_STORAGE_KEY = 'xo-child-enrollment-draft-v1';

export function getDefaultChildEnrollmentValues(): ChildEnrollmentFormValues {
  return {
    nurseryLanguagePref: 'both',
    fullNameAr: '',
    fullNameEn: '',
    dob: '',
    gender: '' as const,
    nationality: 'Egyptian',
    birthCertNumber: '',
    bloodType: '',
    hasAllergies: false,
    allergies: [] as ChildEnrollmentFormValues['allergies'],
    hasConditions: false,
    conditions: [],
    hasMedications: false,
    medications: [],
    dietaryRestrictions: '',
    specialNeeds: '',
    pediatricianName: '',
    pediatricianPhone: '',
    pediatricianClinic: '',
    fatherName: '',
    fatherNationalId: '',
    fatherMobile: '',
    fatherEmail: '',
    fatherOccupation: '',
    fatherWorkplace: '',
    motherName: '',
    motherNationalId: '',
    motherMobile: '',
    motherEmail: '',
    motherOccupation: '',
    motherWorkplace: '',
    addressStreet: '',
    addressDistrict: '',
    addressCity: '',
    addressGovernorate: '',
    emergencyName: '',
    emergencyRelationship: '',
    emergencyMobile: '',
    extraPickups: [],
    previousNursery: '',
    homeLanguage: '',
    toiletTraining: '',
    napMinutes: '',
    temperament: '',
    comfortItems: '',
    separationAnxiety: false,
    religiousDenomination: '',
    religiousHolidays: '',
    culturalPractices: '',
    custodyStatus: 'both',
    consents: {
      photoClassroom: false,
      photoWebsite: false,
      photoSocial: false,
      photoPromo: false,
      fieldTrips: false,
      emergencyMedical: false,
      ambulance: false,
      hospital: false,
      surgery: false,
      dataPrivacy: false,
      behaviorPolicy: false,
      pickupPolicy: false,
      liability: false,
    },
    vaccinationBcg: '',
    vaccinationHepB1: '',
    vaccinationHepB2: '',
    vaccinationHepB3: '',
    vaccinationPolio: '',
    vaccinationDtp: '',
    vaccinationMmr: '',
    signatureName: '',
    signatureDate: new Date().toISOString().slice(0, 10),
  };
}
